# Generated by Django 4.2.5 on 2023-10-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sub_category_details',
            name='product_ram',
            field=models.CharField(max_length=20),
        ),
    ]
